apiVersion: skaffold/v4beta13
kind: Config
metadata:
    name: product-service
build:
    artifacts:
        - image: product-service
          context: .
          docker:
              dockerfile: Dockerfile

    local:
        push: false

manifests:
    rawYaml:
        - k8s/deployment.yaml
        - k8s/service.yaml

deploy:
    kubectl: {}